### ISSUE TITLE
[TRI-1281] feat: Add an optional `to` param to `@trigger.dev/cli init update`

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#484] opened 2023-09-15 21:15 UTC
### Is your feature request related to a problem? Please describe.

When running `npx @trigger.dev/cli@latest update` we should allow you to pass in a `to` option which would set the version to upgrade to (instead of the default which is "latest".

### Describe the solution you'd like to see

* Add a `to` option to the update command, default to "latest": [https://github.com/triggerdotdev/trigger.dev/blob/e350659e244e6976747f726984c83a780ba94882/packages/cli/src/cli/index.ts#L98](https://github.com/triggerdotdev/trigger.dev/blob/e350659e244e6976747f726984c83a780ba94882/packages/cli/src/cli/index.ts#L98)
* If the `to` flag isn't "latest" then get ncu to do the change without spitting out the confirmation. There's a flag called `upgrade` that should work. This file is where edits need to happen: [https://github.com/triggerdotdev/trigger.dev/blob/e350659e244e6976747f726984c83a780ba94882/packages/cli/src/commands/update.ts#L35](https://github.com/triggerdotdev/trigger.dev/blob/e350659e244e6976747f726984c83a780ba94882/packages/cli/src/commands/update.ts#L35)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1281](https://linear.app/triggerdotdev/issue/TRI-1281/feat-add-an-optional-to-param-to-triggerdevcli-init-update)</sub>

**Comment by RamK777-stack** [comment] 2023-09-16 05:22
I have tried, but packages installed versions are same as cli version.

I given npx @trigger.dev/cli@2.1.3 init

<img width="265" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/69167444/f473745f-f1e5-4b0a-946f-e7d2de12c25c">

Am I missing anything?

**Comment by Chigala** [comment] 2023-09-16 05:25
I think it's because you are using the latest CLI @trigger.dev/cli@2.1.3, try using a previous version

**Comment by RamK777-stack** [comment] 2023-09-16 06:16
Yes @Chigala you are right. now able to reproduce

**Comment by RamK777-stack** [comment] 2023-09-16 08:17
I used same version as cli instead of latest, is this correct ? @ericallam @Chigala 

  ```
await addDependencies(resolvedPath, [
    { name: "@trigger.dev/sdk", tag: getVersion() },
    { name: "@trigger.dev/nextjs", tag: getVersion() },
  ]);
```

Previously it was 

```
  await addDependencies(resolvedPath, [
    { name: "@trigger.dev/sdk", tag: "latest" },
    { name: "@trigger.dev/nextjs", tag: "latest" },
  ]);
```

**Comment by Chigala** [comment] 2023-09-16 13:08
Yeah @RamK777-stack. I think I've got a fix for it.

**Comment by matt-aitken** [comment] 2023-09-16 13:25
@Chigala @RamK777-stack thanks for this, really useful info in this and the PR.

There's a major change coming to the CLI: #480. This will be merged in the next couple of days.

This is such a large change that no current CLI PRs will get merged – it would result in tons of conflicts and the underlying code is being changed anyway.

This issue can be worked on after that PR is merged 👍  The method of the fix will be very similar.

**Comment by Chigala** [comment] 2023-09-17 04:35
@matt-aitken That's ohk

**Comment by matt-aitken** [comment] 2023-09-18 12:24
@ericallam do we definitely want this behaviour? Is there a use case outside of our internal development?

I'm concerned that people who globally install the CLI, unfortunately I think there will be some, will be locked. 

Also doesn't it means the message that gets displayed when you run `dev` will be wrong, as it tells you to run `update` but that won't work?

**Comment by ericallam** [comment] 2023-09-18 12:34
Yea good point, maybe instead could we allow an optional CLI flag to allow specifying the version instead of just a hardcoded `latest`?

**Closed** 2023-10-09 16:15 UTC
Labels: enhancement, area/clients, 💎💎 250 points, 🎃 hacktoberfest
