### ISSUE TITLE
bug: TaskIndexingImportError: Could not load the "sharp" module using the linux-x64 runtime

### ISSUE THREAD

**Issue by logimix-v** [triggerdotdev/trigger.dev#1422] opened 2024-10-21 13:26 UTC
### Provide environment information

  System:
    OS: Linux 6.6 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 unknown
    Memory: 5.85 GB / 7.66 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm

### Describe the bug

Can't get the `sharp` module to work no matter what I do.

```
│         x Could not load the "sharp" module using the linux-x64 runtime
│         Possible solutions:
│         - Ensure optional dependencies can be installed:
│             npm install --include=optional sharp
│         - Ensure your package manager supports multi-platform installation:
│             See https://sharp.pixelplumbing.com/install#cross-platform
│         - Add platform-specific dependencies:
│             npm install --os=linux --cpu=x64 sharp
│         - Consult the installation documentation:
│             See https://sharp.pixelplumbing.com/install in src/blog/process_img.ts
```

It is possible that this is somewhat a red herring, as just adding the sharp module by itself to package.json (but not using it) did deploy correctly, however, with the full file it doesn't work.

I've tried all of the install suggestions, I've tried running from within docker (using `node:20`) in addition to my host (macos, m3). Spent over a day fighting with this.

### Reproduction repo

https://github.com/logimix-v/bug-trigger.dev-sharp

### To reproduce

Check out the above repo and run
```
npm i
cd pkgs/trigger
npx trigger.dev@3.0.13 deploy
```
(may need to change project ref)

### Additional information

I've also gotten TLS errors with `--log-level debug`, I'm not sure if they're related. I've tried lots of combinations of states, so this may be due to something else I changed trying to get this to work.

```
◓  Deploying version 20241021.17#1 [depot] launching amd64 machine
| 
◐  Deploying version 20241021.17#1 ERROR: unavailable: tls: failed to verify certificate: x509: certificate signed by unknown authority
| 
| 
| #2 [depot] launching amd64 machine
| 
◑  Deploying version 20241021.17#2 ERROR: unavailable: tls: failed to verify certificate: x509: certificate signed by unknown authority
| 
| ------
|  > [depot] launching amd64 machine:
| ------
| ------
|  > [depot] launching amd64 machine:
| ------
| 
◒  Deploying version 20241021.17.2024/10/21 12:29:04 error releasing builder: unavailable: tls: failed to verify certificate: x509: certificate signed by unknown authority
| 
| Error: unavailable: tls: failed to verify certificate: x509: certificate signed by unknown authority
| 
| Build result {
|   ok: false,
|   error: 'Error building image',
|   logs: '#1 [depot] launching amd64 machine\n' +
|     '#1 ERROR: unavailable: tls: failed to verify certificate: x509: certificate signed by unknown authority\n' +
|     '#2 [depot] launching amd64 machine\n' +
|     '#2 ERROR: unavailable: tls: failed to verify certificate: x509: certificate signed by unknown authority\n' +
|     '------\n' +
|     '> [depot] launching amd64 machine:\n' +
|     '------\n' +
|     '------\n' +
|     '> [depot] launching amd64 machine:\n' +
|     '------\n' +
|     '2024/10/21 12:29:04 error releasing builder: unavailable: tls: failed to verify certificate: x509: certificate signed by unknown authority\n' +
|     'Error: unavailable: tls: failed to verify certificate: x509: certificate signed by unknown authority'
| }
◇  Failed to deploy project
```

The trigger.dev project seems really cool and I'd love to use it! Appreciate any assistance with this.

**Comment by logimix-v** [comment] 2024-10-22 11:49
I was able to make some progress here by promoting all of the dependencies used by my trigger.dev library to top-level workspace dependencies (which didn't seem to be enough) and then also list `sharp` in `additionalPackages: ["sharp"]`, as follows:
```ts
import { defineConfig } from "@trigger.dev/sdk/v3";

export default defineConfig({
  project: "...",
  runtime: "node",
  logLevel: "log",
  // Set the maxDuration to 300 seconds for all tasks. See https://trigger.dev/docs/runs/max-duration
  // maxDuration: 300, 
  retries: {
    enabledInDev: false,
    default: {
      maxAttempts: 3,
      minTimeoutInMs: 1000,
      maxTimeoutInMs: 10000,
      factor: 2,
      randomize: true,
    },
  },
  dirs: ["pkgs"],
  // HOLY ... LIFESAVER
  additionalPackages: ["sharp"]
});
```

I do get deprecation warnings but they just say to use the same field so I'm not sure if it is really an issue.

I still can't tell what the actual issue was or if this is the correct solution. It kind of seems like trigger doesn't work when run as a subpackage in a monorepo, but the docs seem to suggest that is an intended use case.

**Comment by yingzhox** [comment] 2024-10-24 05:19
I get the exact same problem, thanks for the solution!

**Comment by JohnCido** [comment] 2024-10-25 07:47
According to the document [here](https://trigger.dev/docs/config/config-file#external:~:text=Any%20packages%20that%20install%20or%20build%20a%20native%20binary%20should%20be%20added%20to%20external%2C%20as%20native%20binaries%20cannot%20be%20bundled.%20For%20example%2C%20re2%2C%20sharp%2C%20and%20sqlite3%20should%20be%20added%20to%20external.), the `sharp` package should be added as `external`.

**Comment by nicktrn** [comment] 2024-10-25 09:04
We also have a Sharp example that recommends [marking it as external](https://trigger.dev/docs/guides/examples/sharp-image-processing#adding-the-build-configuration). This is required so the `sharp` package can install the (correct) binary. There are a few tricky packages like this which can't be bundled. Marking them as external is generally the solution.

@logimix-v Are you still getting the TLS cert deploy issue?

**Comment by logimix-v** [comment] 2024-10-26 13:36
@yingzhox Ah, thanks! That makes sense.

@JohnCido Thanks for the link, I swear I read through all of the docs but missed the help tip.

@nicktrn Haven't touched this since I got it working a few days ago, so can't comment. The TLS cert issue was harder to reproduce in the first place, but I got it a handful of times when I was first trying. Let's say I haven't seen it anymore, and I'll make a new ticket for it if I run into it again. Thanks for following up.

Noted. So the conclusion is that marking it `external` is preferable over using `additionalPackages`? Can you comment on the difference between these two things? Also it seems like `external` uses `package.json` and not `package-lock.json` - is my understanding correct? What is the best way to get reproducible builds?

**Comment by nicktrn** [comment] 2024-10-27 12:44
Hey @logimix-v - I'll quote from our docs to answer this and provide a summary of the differences.

`additionalPackages`:
> This allows you to _include additional packages in the build that are not automatically included via imports_. This is useful if you want to install a package that includes a CLI tool that you want to invoke in your tasks via `exec`. We will try to automatically resolve the version of the package but **you can specify the version by using the `@` symbol**

`external`:
> When a package is _excluded from the bundle_, it will be added to a dynamically generated package.json file in the build directory. The version of the package **will be the same as the version found in your `node_modules` directory**.


In summary:
- `additionalPackages` is best used for external tools that you don't import but may use in scripts, e.g. wrangler. Due to this, you can also specify the version to use, unless you're happy with `latest`.
- `external` will only affect packages used via imports - we will exclude them from the bundle. This is useful if a package doesn't play well with bundling. Error messages like the one you received are good indicators here. We will use the correct version as per your package manager's _lockfile_ by checking the version found in `node_modules` after running install.
- In both cases we will add the package to the resulting `package.json` - the difference is where the version comes from.

For reproducible builds, marking packages as external will have no effect on versions used. The only important thing is to always use a specific version for additional packages, for example:

```ts
build: {
  extensions: [additionalPackages({ packages: ["wrangler@1.19.0"] })],
}
```

**Closed by nicktrn** 2024-10-27 12:44 UTC
